# Generated by Django 4.2.9 on 2026-01-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_student',
        ),
    ]
