# Generated by Django 4.2.9 on 2026-01-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_unique_active_booking_per_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RebookingPermission',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('subject', models.CharField(max_length=100, db_index=True)),
                ('teacher_external_id', models.CharField(max_length=255, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='rebooking_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rebooking_permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rebookingpermission',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_rebooking_permission_per_student_subject'),
        ),
        migrations.AddIndex(
            model_name='rebookingpermission',
            index=models.Index(fields=['student', 'subject'], name='rebook_permi_student_77ff30_idx'),
        ),
        migrations.AddIndex(
            model_name='rebookingpermission',
            index=models.Index(fields=['teacher_external_id', 'subject'], name='rebook_permi_teacher_3d0c89_idx'),
        ),
    ]
