# Generated by Django 4.2.9 on 2026-01-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rebookingpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebookingpermission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rebooking Permission', 'verbose_name_plural': 'Rebooking Permissions'},
        ),
        migrations.RenameIndex(
            model_name='rebookingpermission',
            new_name='rebooking_p_student_2c4b26_idx',
            old_name='rebook_permi_student_77ff30_idx',
        ),
        migrations.RenameIndex(
            model_name='rebookingpermission',
            new_name='rebooking_p_teacher_f174de_idx',
            old_name='rebook_permi_teacher_3d0c89_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('absent', 'Absent')], db_index=True, default='confirmed', max_length=20),
        ),
    ]
