# Generated by Django 4.2.9 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_rebookingpermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='absent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
