# Generated by Django 4.2.9 on 2026-01-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='subject',
            field=models.CharField(db_index=True, default='General', max_length=100),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['faculty', 'subject', 'is_available'], name='slots_faculty_5192e0_idx'),
        ),
    ]
