# Generated by Django 4.2.9 on 2026-01-13 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_for_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StudentTeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_external_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student-Teacher Assignment',
                'verbose_name_plural': 'Student-Teacher Assignments',
                'db_table': 'student_teacher_assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'teacher_external_id'], name='student_tea_student_3b5f0c_idx'), models.Index(fields=['teacher_external_id', 'subject'], name='student_tea_teacher_8d27e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentteacherassignment',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_assignment'),
        ),
    ]
